# netlify.toml

# Build settings
[build]
  # Command to run your build
  command = "npm run build"

  # Directory to publish after building
  publish = "/opt/build/repo/build"

  # Ignore warnings during the build process
  ignore_warnings = true

# You can add other settings such as redirects, headers, etc. below if needed